### ISSUE TITLE
Feature request: `gg` fast-scrolls to the top

### ISSUE THREAD

**Issue by benwoodward** [psliwka/vim-smoothie#1]
Not a super-necessary feature, but sublime text does this and it gives you a sense of how long the file is when you see it scroll past.

**Comment by psliwka** [comment]
This is a reasonable feature request indeed. It does, however, pose several implementation challenges:

1. Currently, the plugin mechanics rely on scrolling, i.e. moving the window over the buffer. The cursor follows the window as a side effect, being subject to various modifiers such as scrolloff and startofpage. Commands such as `gg` work the other way around - they move the cursor itself, which is being followed by the window. To handle them reliably, the plugin will need to learn this difference, probably by switching between different scrolling styles depending on what command triggered movement.
2. Cursor movement commands are frequently used to operate on ranges, f.ex. `gggqG`. The plugin will need to detect such cases, and either skip the animation, or delay executing further commands until the animation ends. Otherwise, subsequent commands would be applied to incorrect ranges.
3. Any command replaced by _vim-smoothie_ should be 100% compatible with the original one. In case of `gg`, that means supporting `[count]` and `'startofline'` at least.

Similar issues apply to implementing other cursor movement commands, such as f.ex. `[[` and `{`.

**Comment by subnut** [comment]
@benwoodward Try #21 with the following configuration -
```vim
silent! map <unique> gg         <Plug>(Smoothie_gg)
silent! map <unique> G          <Plug>(Smoothie_G)
```

**Comment by benwoodward** [comment]
@subnut Works well! Great work.

**Comment by psliwka** [comment]
`gg` and `G` support has landed on master 🎉 To enable it, you can either set up custom mappings in your vimrc (as @subnut described above), or you can `let g:smoothie_experimental_mappings=v:true` and have them defined automatically along with the rest of default mappings.
