### ISSUE TITLE
Feature request: scroll past the end

### ISSUE THREAD

**Issue by CarbonaraJack** [psliwka/vim-smoothie#11]
Hello, I am currently in the process of learning VIM and your awesome plugin helps me a lot. Before installing smoothie I would always feel lost when scrolling though text and I am very grateful for that.

Would it be possible to implement scrolling past the end of files? In another issue you mention that smoothie only works with commands that move the window over the buffer but not by moving the cursor. Does this apply to zz, zt and zb as well?

**Comment by psliwka** [comment]
Hi, and thanks for the kind words :)

> Would it be possible to implement scrolling past the end of files?

Ah, yes. I see that original `^F` can scroll past the EOL, eventually leaving only one last line visible on screen. Since the goal of this project is 100% compatibility with native commands, I'd say this is certainly a valid request.

> In another issue you mention that smoothie only works with commands that move the window over the buffer but not by moving the cursor. Does this apply to zz, zt and zb as well?

`zz` and friends are scrolling commands indeed, and should be quite easy to implement. I'd be glad to review a PR adding them ;)

**Comment by subnut** [comment]
> Would it be possible to implement scrolling past the end of files?

@CarbonaraJack I have tried to implement this feature in commit `2bdd74f` in PR #21 
Please test for any bugs in the implementation. Thank you.

**Comment by psliwka** [comment]
Marking this issue as resolved. Progress on `zz` and friends will be tracked in #26.
